app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/external-resource', 'ExternalController@index');
Route::get('/external-resource/external', 'ExternalController@external');
Route::get('/external-resource/test', 'ExternalController@test');

Route::any('/chart', 'ChartController@index');
Route::any('/chart/get', 'ChartController@getChart');
Route::any('/chart/get2', 'ChartController@getChart2');
Route::resource('/calendar', 'CalendarController');
//Route::resource('/user', 'UserController');
Route::get('/events', 'CalendarController@calendar');
Route::get('/choose', 'CalendarController@choose');

Route::resource('/manager/calendar', 'CalendarController', ['except' => 'show']);
Route::get('/manager/calendar/lists', 'CalendarController@lists');
Route::get('/manager/calendar/choose', 'CalendarController@choose');
Route::any('/manager/user/paginate', 'UserController@paginate');
Route::get('/manager/user', 'UserController@index');

Route::get('/test', function (\Illuminate\Http\Request $request) {

    $type = function ($o) {
        return $o['type'] == 1;
    };

    $limit = function ($o) {
        return $o['limit'] <= 5;
    };

    $expiration = function ($o) {
        return $o['expiration'] == null || $o['expiration'] <= 10;
    };

    $collection = [
        ['limit' => 10, 'type' => 3, 'expiration' => 10],
        ['limit' => 1, 'type' => 1, 'expiration' => 30],
        ['limit' => 5, 'type' => 2, 'expiration' => 7],
        ['limit' => 9, 'type' => 1, 'expiration' => 2],
        ['limit' => 1, 'type' => 1, 'expiration' => null],
        ['limit' => 1, 'type' => 1, 'expiration' => 0],
        ['limit' => 7, 'type' => 1, 'expiration' => 0],
    ];

    $mostProx = function ($arr, $limit) {

        if (count($arr) == 0) return;

        usort($arr, function ($a, $b) {
            return $a['limit'] > $b['limit'];
        });

        $c = $arr[0];
        for ($i = 0; $i < count($arr); $i++) {
            if ($arr[$i]['limit'] <= $limit) {
                $c = $arr[$i];
                continue;
            }

            return $c;
        }
    };

    dd($mostProx($collection, 6));
    dd($collection);

    $filters = [$type, $limit, $expiration];

    foreach ($filters as $filter) {

//        if (count($collection) <= 1) break;

        $collection = array_filter($collection, $filter);
        print_r($collection);
        echo "<br>";
    }

    dd($collection);

    return $request->all();
});

Route::put('/test/{id}', function (\Illuminate\Http\Request $request) {
//    return new \App\User(['name'=>'Loro']);
    return $request->all();
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //
});

app/Http/Controllers/CalendarController.php
<?php
/**
 * Created by PhpStorm.
 * User: Lourivaldo
 * Date: 23/04/2016
 * Time: 09:08
 */

namespace App\Http\Controllers;

use App\Http\Requests\CreateEventRequest;
use App\Http\Requests\ListsEventRequest;
use App\Api;
use App\Event;
use App\RepeatType;
use Carbon\Carbon;
use Illuminate\Http\Request;

class CalendarController extends Controller
{

    private $js = ['requireJS' => ['calendar/index.js']];

    public function index()
    {
        return view('calendar.index');
    }

    public function create()
    {
        $repeatsTypes = RepeatType::types();
        $apis = Api::all();

        return view('calendar.create', compact(['apis', 'repeatsTypes']), ['requireJS' => ['calendar/create.js']]);
    }

    public function store(CreateEventRequest $request, Event $event)
    {
        if ($event = $event->create($request->all())) {
            $event->apis()->sync($request->input('apis'));
        }

        return redirect("/manager/calendar");
    }

    public function edit($id)
    {
        /** @var Event $event */
        $data = Event::with('repeat')->findOrFail($id);

        $repeatsTypes = RepeatType::types();
        $apis = Api::all();
        return view('calendar.edit', compact(['data', 'apis', 'repeatsTypes']), ['requireJS' => ['calendar/create.js']]);
    }

    public function update(Request $request, $id)
    {
        $event = Event::with('repeat')->findOrFail($id);
//        dd($request->all());
        if ($event->update($request->all())) {
            $event->apis()->sync($request->get('apis'));
            if ($request->has('repeatable') && $request->has('repeat')) {
                //@Todo: tirar daqui
                $ever = $request->input('repeat.end_type') == REPEAT_TYPE_EVER ? 1 : 0;
                $event->repeat()->updateOrCreate([], array_merge($request->get('repeat'), ['ever' => $ever]));
            } else if ($event->has('repeat')) {
                $event->repeat()->forceDelete();
            }
            return redirect('/manager/calendar');
        } else {
            return back()->withErrors();
        }
    }

    public function lists(ListsEventRequest $request)
    {
//        return Event::holidays();
        $start = $request->get('start');
        $end = $request->get('end');
        $start = Carbon::createFromFormat("Y-m-d", $start);
        $end = Carbon::createFromFormat("Y-m-d", $end);
        return Event::getEvents($start, $end);
    }

    //Api ativa > Feriado > Horario > Usuario > Agencia
    //Api ativa > !Horario
    //Api ativa > !Usuario
    //Api ativa > !Agencia
    public function choose()
    {
        /** @var Api $activeApis */
        $activeApis = /*Cache::remember('', 1, function () {
            return */
            Api::select('status')->where('status', '=', 1)->get();
        /*});*/

        if ($activeApis->count() > 1) {
            //1Checar Feriado - usar apenas definidas
            //1.1 se apenas uma
            //1.1.1 busca por ela
            //1.2 se nao
            //2 busca pelo horario

            $date = new Carbon();
            $events = Event::apisOn($date)->toArray();

            return $events;

        } else if ($activeApis->count() == 1) {
            //Faz consulta com a unica disponivel
            dd($activeApis->first());
        } else {
            //Nao faz consulta
        }
    }
}

resources/views/calendar/partials/form-repeat.blade.php
<div class="panel panel-white">
    <div class="panel-heading clearfix">
        <h4 class="panel-title">
            {!! Form::checkbox('repeatable',1,(isset($data) && is_null($data->repeat) ? 0 : 1)) !!} {!! Form::label('repeat','Repetir') !!}
        </h4>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="form-group">
                    {!! Form::label('repeat[repeats_types_id]','Repetição:') !!}
                    {!! Form::select('repeat[repeats_types_id]',$repeatsTypes,null,['class'=>'form-control', 'id'=>'repeat-type','style'=>'width:inherit;display:inline;display:inline']) !!}
                </div>

                <div class="form-group" id="repeat-target-2" style="display: none;">
                    {{--Dia da semana--}}
                    {{--@Todo:check for dow from start date--}}
                    {!! Form::label('repeat[dows][]','Repete:') !!}
                    {!! Form::checkbox('repeat[dows][]', 0, null, ['id'=>'dows-0']) !!}{!! Form::label('dows-0','D') !!}
                    {!! Form::checkbox('repeat[dows][]', 1, null, ['id'=>'dows-1']) !!}{!! Form::label('dows-1','S') !!}
                    {!! Form::checkbox('repeat[dows][]', 2, null, ['id'=>'dows-2']) !!}{!! Form::label('dows-2','T') !!}
                    {!! Form::checkbox('repeat[dows][]', 3, null, ['id'=>'dows-3']) !!}{!! Form::label('dows-3','Q') !!}
                    {!! Form::checkbox('repeat[dows][]', 4, null, ['id'=>'dows-4']) !!}{!! Form::label('dows-4','Q') !!}
                    {!! Form::checkbox('repeat[dows][]', 5, null, ['id'=>'dows-5']) !!}{!! Form::label('dows-5','S') !!}
                    {!! Form::checkbox('repeat[dows][]', 6, null, ['id'=>'dows-6']) !!}{!! Form::label('dows-6','S') !!}
                </div>

                <div class="form-group" id="repeat-target-3" style="display: none;">
                    {{--Dia do mes--}}
                    {!! Form::label('repeat[dom]','Repetir:') !!}
                    {!! Form::radio('repeat[dom]', 0, null, ['id'=>'dom-0']) !!}{!! Form::label('dom-1','dia da semana') !!}
                    {!! Form::radio('repeat[dom]', 1, null, ['id'=>'dom-1']) !!}{!! Form::label('dom-0','dia do mês') !!}
                </div>

                <hr>
                <div>
                    <strong>Termina:</strong>
                </div>

                <div class="col-sm-12 col-md-12">
                    <div class="form-group">
                        {!! Form::radio('repeat[end_type]',REPEAT_TYPE_EVER,1,['class'=>'form-control']) !!}
                        {!! Form::label('end_type','Nunca') !!}
                    </div>

                    <div class="form-group">
                        {!! Form::radio('repeat[end_type]',REPEAT_TYPE_OCCURRENCES,null,['class'=>'form-control']) !!}
                        {!! Form::label('occurrences','Após:') !!}
                        {!! Form::number('repeat[occurrences]',null,['min'=>'0', 'max'=>'999999','class'=>'form-control','style'=>'width:inherit;display:inline']) !!}
                        {!! Form::label('occurrences','ocorrências') !!}
                    </div>

                    <div class="form-group">
                        {!! Form::radio('repeat[end_type]',REPEAT_TYPE_DATE,null,['class'=>'form-control','style'=>'width:inherit;display:inline']) !!}
                        {!! Form::label('repeat[end]','Em') !!}
                        {!! Form::text('repeat[end]',null,['class'=>'form-control','style'=>'width:inherit;display:inline']) !!}
                    </div>
                </div>

                {{--<div class="form-group">
                    <strong>Resumo:</strong><span>resumo aqui</span>
                </div>--}}
            </div>
        </div>

    </div>
</div>

resources/views/calendar/partials/form.blade.php
<div class="row">
    @if(isset($errors))
        @foreach($errors->all() as $error)
            {!! $error !!}
        @endforeach
    @endif

    <div class="col-sm-12 col-md-6">
        <div class="panel panel-white">
            <div class="panel-heading clearfix">
                <h4 class="panel-title">Evento</h4>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12 col-md-12">
                        <div class="form-group">
                            {!! Form::hidden('apis') !!}
                            @foreach($apis as $api)
                                {!! Form::checkbox('apis[]', $api->id, isset($data)? in_array($api->id, $data->apis()->select('id')->lists('id')->toArray()) : null, ['class'=>'', 'id'=>"apis-$api->id"]) !!}
                                {!! Form::label("apis-$api->id", $api->name) !!}
                            @endforeach
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-12">
                        <div class="row">
                            <div class="col-sm-12 col-md-5">
                                <div class='input-group date datetime-picker----'>
                                    {!! Form::text('start', null, ['id'=>'start','class'=>'form-control']) !!}
                                    <span class="input-group-addon"><span
                                                class="glyphicon glyphicon-calendar"></span></span>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-2">
                                {!! Form::label('start','até') !!}
                            </div>
                            <div class="col-sm-12 col-md-5">
                                <div class='input-group date datetime-picker----'>
                                    {!! Form::text('end',null,['id'=>'end','class'=>'form-control']) !!}
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-12">
                        <div class="form-group">
                            {!! Form::label('color','Cor') !!}
                            {!! Form::color('color', null,['class'=>'form-control']) !!}
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-12">
                        <div class="form-group">
                            {!! Form::hidden('all_day',0) !!}
                            {!! Form::checkbox('all_day',1,null) !!}
                            {!! Form::label('all_day','Dia inteiro') !!}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12 col-md-12">
                        {!! Form::hidden('status',0) !!}
                        <div class="form-group">
                            {!! Form::checkbox('status',1,1) !!}
                            {!! Form::label('status','Ativar') !!}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12 col-md-12">
                        <div class="form-group">
                            <a href="{{ route('manager.calendar.index') }}" class="btn btn-primary">Cancelar</a>
                            {!! Form::submit("Salvar", ['id'=>'save','class' => 'btn btn-success']) !!}
                        </div>
                    </div>
                </div>

            </div>
        </div>


    </div>

    <div class="col-sm-12 col-md-6">
        @include('calendar.partials.form-repeat')
    </div>

</div>